application: isb-cgc
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: MySQLdb
  version: "latest"
- name: ssl
  version: "latest"
- name: pycrypto
  version: "2.6"
- name: endpoints
  version: 1.0

builtins:
- django_wsgi: on

handlers:
- url: /static
  static_dir: static
- url: /_ah/spi/.*
  script: api.APPLICATION
- url: /.*
  script: main.application
- url: /static/admin
  static_dir: static/admin
  expiration: 0

env_variables:
  DJANGO_SETTINGS_MODULE: 'GAE_Django17.settings'
