application: striking-berm-771
version: django17
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: MySQLdb
  version: "latest"
- name: ssl
  version: "latest"
- name: pycrypto
  version: "2.6"

builtins:
- django_wsgi: on

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: main.application
- url: /static/admin
  static_dir: static/admin
  expiration: 0

